### ISSUE TITLE
Jest fails to parse TSX

### ISSUE THREAD

**Issue by x86chi** [preactjs/enzyme-adapter-preact-pure#97]
Hello, I'm trying to run tests with Jest in a Preact app with TypeScript. I get a Jest encountered an unexpected token error :

```
FAIL  src/app/app.test.tsx
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, 
     e.g. it's not plain JavaScript.
...
    Details:

    src/app/app.test.tsx:10
        const wrapper = enzyme_1.mount(<app_1.default optOutUrl="none"/>);
                                       ^

    SyntaxError: Unexpected token <

    at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1059:14)
```

After seen [TypeScript example](https://github.com/preactjs/enzyme-adapter-preact-pure/tree/master/examples/typescript) in this enzyme-adapter-preact-pure, I Changing jsx option to react in `tsconifg.json`. But It not helpful for my project environment:
```
Cannot find module 'react' from 'styled.js'

    However, Jest was able to find:
        './styled.js'
        './styled.js.flow'
        './styled.js.map'

    See https://jestjs.io/docs/en/configuration#modulefileextensions-array-string

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:276:11)
      at Object.<anonymous> (node_modules/linaria/src/react/styled.js:3:15)
```

In the above error, it says that react parsing failed in the styled component related file. (I’m use styled components from `linaria/react` with [custom Preact typing](https://github.com/reflation/extension/blob/routers/login/test/src/utils/styled.ts).) this issue not appear in development and production environment.

I also tried using babel-jest with below config. But I got the same message as the first error log.

```
“transform”: {
      “^.+\\.ts$”: “babel-jest”
    }
```

**Comment by robertknight** [comment]
Hello,

First of all, your problem doesn't seem like it relates to this project directly. It seems like you're having trouble getting TypeScript + JSX to work inside Jest. I would recommend asking for help in Jest's community forums/chat as you're more likely to find the right experts.

From the error messages you posted,  it seems like Jest is parsing a JavaScript file containing JSX expressions and it isn't set up to handle that. To me this suggests that either you need to configure TypeScript to output plain JavaScript (not JavaScript + JSX) or you need to use another tool to convert TypeScript's JavaScript + JSX output to plain JavaScript. I guess this is what you were trying to do with babel-jest? One possible issue I can see is that your regular expression (`^.+\\.ts$`) does not match files than end with `.tsx`.

I'm closing this issue because I don't think there is an issue with the adapter, but please do post a comment here when you figure the problem out.

**Comment by x86chi** [comment]
I solved it by insert the `babel-config: true` in jest config.

The difference is that the `babel-jest` do not specified directly as a transform, and keep the ts-jest preset.

```json
"preset": "ts-jest",
  "globals": {
    "ts-jest": {
      "babelConfig": true
  }
},
```
